### ISSUE TITLE
missing language detection into the tracks (ex. m2ts files)

### ISSUE THREAD

**Issue by mr-bolle** [jlesage/docker-tsmuxer#1]
Hi Jocelyn, 

thank you first for your amazing and usefull images what you puplished.

Steps to reproduce:
1. run the docker-tsmuxer container
2. open GUI over VNC or Webclient
3. add a new imput file (ex. 00003.m2ts)
4. the column 'lang' is empty

*What is the current used tsmuxer version into this image?*   **edit: version 2.6.11**  --> could you please upgrade this application to 2.6.12, maybe with the last release it fix this issue

*Note:* with a other source format (ex. *.ts) with the tsmuxer session i get a language responce

I use the Windows GUI Application v2.6.12, and open the same example file (ex. 00003.m2ts). And this Application read the Langnuage from the Tracks.

![13-10-_2018_08-49-31](https://user-images.githubusercontent.com/22414212/46903019-69993300-cecf-11e8-8844-dd92ebd474df.jpg)

**Comment by jlesage** [comment]
I confirm that I have the same issue as you.  However, the issue seems really related to tsMuxeR itself, since I can also reproduce on a standard Ubuntu machine.

Version 2.6.12 is for Windows only.  There is no such version on Linux.

Do you know any active forum for tsmuxer?  Maybe you can try to post your issue there.

**Comment by mr-bolle** [comment]
Hi, there is a Linux Version available. 
Could you try this, unfortunately with my skills I don't know how to integrate it into the image.

https://www.videohelp.com/software/tsMuxeR

**Comment by jlesage** [comment]
If you look at the link for the Linux version, you see that it points to https://www.videohelp.com/download/tsMuxeR_2.6.11.tar.gz.

Also, on the same page, you can see the changelog:
```
------------ Network Optix tsMuxeR 2.6.12 ----------------------
- several minor bugs fixed

(no linux or mac versions released yet)
```

**Comment by mr-bolle** [comment]
Presumably there will be no update from tsMuxeR for Linux
