### ISSUE TITLE
FEATURE REQUEST: Add option to encrypt channel

### ISSUE THREAD

**Issue by frakman1** [jlesage/docker-tsmuxer#3]
Given a key, allow user to encrypt a channel including the correct MPEG headers/PIDS that describe an encrypted channel.

**Comment by jlesage** [comment]
This project is about packaging tsmuxer into a Docker container.  So it's unfortunately not the right place to ask for new tsmuxer features.

**Comment by frakman1** [comment]
Oh OK. I followed the github link from the Info pane of the App in Community Apps in Unraid.
