### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by rome1983** [jlesage/docker-tsmuxer#4]
Hi, would it be possible to build tsmuxer container with appimage? Thanks

**Comment by jlesage** [comment]
Do you mean integrating the appimage into a container ?  What would be the benefit ?

**Comment by rome1983** [comment]
I would like to get a updated version working directly on my nas if possible. Your current container works but to outdated to deal with Dolby vision files.

**Comment by jlesage** [comment]
Ok, see issue https://github.com/jlesage/docker-tsmuxer/issues/5.

**Comment by nc88keyz** [comment]
> I would like to get a updated version working directly on my nas if possible. Your current container works but to outdated to deal with Dolby vision files.

3d muxing with atmos is broken as well. Creates a mess. Work perfectly in the justdan96 nightlies for windows/linux/mac. But i much prefer to do those tasks via docker on the nas.
