### ISSUE TITLE
[Update] v2.6.11 ==> v2.6.16

### ISSUE THREAD

**Issue by the-hotmann** [jlesage/docker-tsmuxer#5]
Update to 2.6.16 pls, adds support for nice HDR features which I sometimes use :)

Thanks in advance!

**Comment by jlesage** [comment]
Ae you talking about the nightly builds from https://github.com/justdan96/tsMuxer ?

**Comment by the-hotmann** [comment]
Sorry, yes - should have specified that. The old source/maintainer does not develope it further and the changelog of the new "taken over source" is pretty neat: https://github.com/justdan96/tsMuxer/blob/master/CHANGELOG.md
I know it is labled as nightly, but seems to be stable for me (tested on Windows).

Just noticed, that issue on the docker-base image: https://github.com/jlesage/docker-baseimage-gui/issues/67 - it seems to be the same request and should belong here into [docker-tsmuxer](https://github.com/jlesage/docker-tsmuxer/).

**Comment by jlesage** [comment]
Ok I will look at this.  I was waiting for the project to have stable versions, but I guess I can make an exception :)

The problem I see using nightly builds is that it's easy to get a broken version...

**Comment by nc88keyz** [comment]
any futher progress on a updated image using the new nightly builds as a base from justdan96.

**Comment by jlesage** [comment]
Latest image now uses the open source version!
